default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: volshebno
  username: postgres
  password: postgres

staging:
  <<: *default
  database: volshebno
  username: volshebno
  password: volshebno

production:
  <<: *default
  database: volshebno
  username: volshebno
  password: 157b1285b7627df951b18acfa6026054
